# Generated by Django 4.2.2 on 2023-06-21 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=20, verbose_name='ID чата клиента')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя клиента')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название мероприятия')),
                ('date', models.DateField(verbose_name='Дата мероприятия')),
                ('start_time', models.TimeField(verbose_name='Время начала мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название презентации')),
                ('annotation', models.TextField(verbose_name='Аннотация')),
                ('start_time', models.TimeField(verbose_name='Время начала презентации')),
                ('end_time', models.TimeField(verbose_name='Время окончания презентации')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetups.event', verbose_name='Мероприятие')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='meetups.client', verbose_name='Спикер')),
            ],
            options={
                'verbose_name': 'Презентация',
                'verbose_name_plural': 'Презентации',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Записан')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetups.client', verbose_name='Клиент')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetups.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Посетитель',
                'verbose_name_plural': 'Посетители',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Задан')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='meetups.client', verbose_name='Клиент')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='meetups.presentation', verbose_name='Презентация')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Поставлен')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='meetups.client', verbose_name='Клиент')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='meetups.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='visitors',
            field=models.ManyToManyField(related_name='events', through='meetups.Visitor', to='meetups.client', verbose_name='Посетители'),
        ),
    ]
