# Generated by Django 4.2.2 on 2023-06-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='surname',
            new_name='last_name',
        ),
    ]
