# Generated by Django 4.2.2 on 2023-06-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_alter_client_options_event_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={'verbose_name': 'Доклад', 'verbose_name_plural': 'Доклады'},
        ),
        migrations.AddField(
            model_name='presentation',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Завершен'),
        ),
    ]
