# Generated by Django 4.2.2 on 2023-06-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_alter_presentation_options_presentation_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='meetups.event', verbose_name='Мероприятие'),
        ),
    ]
