# Generated by Django 4.2.2 on 2023-06-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_alter_presentation_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='text', max_length=50, verbose_name='Заголовок вопроса'),
            preserve_default=False,
        ),
    ]
