# Generated by Django 4.2.2 on 2023-06-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_question_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
    ]
