# Generated by Django 4.2.2 on 2023-06-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0010_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыт'),
        ),
    ]
